### ISSUE TITLE
Panic when loading dahdi kmod

### ISSUE THREAD

**Issue by fireglow** [HardenedBSD/hardenedBSD#201] opened 2016-05-26 14:46 UTC
This panic got introduced after the machine was switched from FreeBSD stable/10 to 10.3-STABLE-HBSD.

- FreeBSD:
  - 10.3-STABLE-HBSD FreeBSD 10.3-STABLE-HBSD #0 8cb1ce7(hardened/10-stable/master)
- Kernel:
  - HARDENEDBSD
  - Also happens with all PAX_* options disabled:
```
    # HardenedBSD hardening options
options         PAX                     # PaX framework
#options        PAX_SYSCTLS             # sysctls for run-time options
#options        PAX_ASLR                # Address Space Layout Randomization
#options        PAX_NOEXEC              # Remove WX pages from user-space and enforce W^X
#options        PAX_HARDENING           # Various hardening options
#options        PAX_SEGVGUARD           # prevent brute-force attacks
options         HBSD_DEBUG
options         INVARIANTS              # Check and enforce proper kernel state.
options         INVARIANT_SUPPORT
```

- dahdi:
  - misc/dahdi 2.4.0rc5_6
  - misc/dahdi-kmod 2.4.0rc5_7
 
```
~ # ❯❯❯ uname -a
FreeBSD void.lan 10.3-STABLE-HBSD FreeBSD 10.3-STABLE-HBSD #0 8cb1ce7(hardened/10-stable/master): Thu May 26 14:27:12 CEST 2016     builder@void.lan:/usr/obj/usr/src/sys/HARDENEDBSD32  amd64
```
 
```
~ # ❯❯❯ service dahdi onestart
Starting dahdi.
<6>dahdi: Telephony Interface Registered on major 196
<6>dahdi: Version: 2.4.0-rc5
wctdm0: vendor=e159 device=1 subvendor=b119
wctdm0: <Wildcard TDM400P REV I> port 0xd000-0xd0ff mem 0xf7d00000-0xf7d00fff irq 16 at device 0.0 on pci3
<6>Freshmaker version: 73
<6>Freshmaker passed register test
<6>Module 0: Installed -- AUTO FXO (FCC mode)
<6>Module 1: Installed -- AUTO FXO (FCC mode)
<6>Module 2: Installed -- AUTO FXO (FCC mode)
<6>Module 3: Installed -- AUTO FXO (FCC mode)
<6>Found a Wildcard TDM: Wildcard TDM400P REV I (4 modules)
panic: sx_slock() by idle thread 0xfffff800031ac000 on sx chan_lock @ /wrkdirs/usr/ports/misc/dahdi-kmod/work/dahdi-freebsd-complete-2.4.0-rc5+2.4.0-rc1/freebsd/freebsd/dahdi/../../drivers/dahdi/dahdi-base.c:8841
cpuid = 0
KDB: stack backtrace:
#0 0xffffffff80997330 at kdb_backtrace+0x60
#1 0xffffffff8095c536 at vpanic+0x126
#2 0xffffffff8095c409 at kassert_panic+0x139
#3 0xffffffff80963617 at _sx_slock+0xe7
#4 0xffffffff8206e732 at process_masterspan+0x62
#5 0xffffffff8206d2eb at dahdi_receive+0x39b
#6 0xffffffff820643b3 at wctdm_interrupt+0x1103
#7 0xffffffff809265ec at intr_event_handle+0x8c
#8 0xffffffff80e9ba68 at intr_execute_handlers+0x48
#9 0xffffffff80e9f633 at lapic_handle_intr+0x73
#10 0xffffffff80d5a784 at Xapic_isr1+0xa4
#11 0xffffffff80985f49 at sched_idletd+0x419
#12 0xffffffff80923f04 at fork_exit+0x84
#13 0xffffffff80d5a61e at fork_trampoline+0xe
Uptime: 8m10s
```

The dahdi pkgs where built by 
`FreeBSD 11.0-CURRENT-HBSD #2 ca9b345(hardened/current/master)-dirty`
Poudriere jail: 10.3-RELEASE-p3, ports tree hardenedbsd-ports at d114b3a62351eae9f8526f37b51cc0d43609c4f9

@lattera mentioned that it might be hard to debug this issue without the corresponding hardware.

**Comment by lattera** [comment] 2016-05-26 15:35
Looks like this is yet another INVARIANTS-related bug. Waiting for confirmation from @fireglow if this is reproducible in vanilla FreeBSD with INVARIANTS + INVARIANT_SUPPORT enabled in the kernel.

**Comment by fireglow** [comment] 2016-05-26 15:35
@lattera gave a crucial hint to track down the origin of this issue:
No crash with:
```
# HardenedBSD hardening options
options         PAX                     # PaX framework
#options        PAX_SYSCTLS             # sysctls for run-time options
#options        PAX_ASLR                # Address Space Layout Randomization
#options        PAX_NOEXEC              # Remove WX pages from user-space and enforce W^X
#options        PAX_HARDENING           # Various hardening options
#options        PAX_SEGVGUARD           # prevent brute-force attacks
options         HBSD_DEBUG
#options        INVARIANTS              # Check and enforce proper kernel state.
#options        INVARIANT_SUPPORT
options         PAX_INSECURE_MODE
```

**Comment by opntr** [comment] 2016-05-26 18:56
"FreeBSD 11.0-CURRENT-HBSD #2 ca9b345(hardened/current/master)-dirty"

Why are you packages built on 11-CURRENT on 10-STABLE? They are not backward compatible.

**Comment by opntr** [comment] 2016-05-26 18:57
Have you rebuilt the dahdi-kmod based on 10-STABLE?

**Comment by fireglow** [comment] 2016-05-26 19:53
Can confirm that it also crashes on 10/stable with FreeBSD packages.
```
~ # ❯❯❯ uname -a
FreeBSD void 10.3-STABLE FreeBSD 10.3-STABLE #0 r300749: Thu May 26 19:43:12 CEST 2016     builder@void:/usr/obj/usr/src/sys/INVARIANTS  amd64
~ # ❯❯❯ pkgs | grep dahdi
misc/dahdi 2.4.0rc5_6 (FreeBSD)
misc/dahdi-kmod 2.4.0rc5_7 (FreeBSD)
~ # ❯❯❯ service dahdi onestart
Starting dahdi.
<6>dahdi: Telephony Interface Registered on major 196
<6>dahdi: Version: 2.4.0-rc5
wctdm0: vendor=e159 device=1 subvendor=b119
wctdm0: <Wildcard TDM400P REV I> port 0xd000-0xd0ff mem 0xf7d00000-0xf7d00fff irq 16 at device 0.0 on pci3
<6>Freshmaker version: 73
<6>Freshmaker passed register test
<6>Module 0: Installed -- AUTO FXO (FCC mode)
<6>Module 1: Installed -- AUTO FXO (FCC mode)
<6>Module 2: Installed -- AUTO FXO (FCC mode)
<6>Module 3: Installed -- AUTO FXO (FCC mode)
<6>Found a Wildcard TDM: Wildcard TDM400P REV I (4 modules)
panic: sx_slock() by idle thread 0xfffff800031ac000 on sx chan_lock @ /wrkdirs/usr/ports/misc/dahdi-kmod/work/dahdi-freebsd-complete-2.4.0-rc5+2.4.0-rc1/freebsd/freebsd/dahdi/../../drivers/dahdi/dahdi-base.c:8841
cpuid = 0
KDB: stack backtrace:
#0 0xffffffff80984780 at kdb_backtrace+0x60
#1 0xffffffff809495e6 at vpanic+0x126
#2 0xffffffff809494b9 at kassert_panic+0x139
#3 0xffffffff80950757 at _sx_slock+0xe7
#4 0xffffffff81e57732 at process_masterspan+0x62
#5 0xffffffff81e562eb at dahdi_receive+0x39b
#6 0xffffffff81e4d3b3 at wctdm_interrupt+0x1103
#7 0xffffffff809137ec at intr_event_handle+0x8c
#8 0xffffffff80e795b8 at intr_execute_handlers+0x48
#9 0xffffffff80e7d183 at lapic_handle_intr+0x73
#10 0xffffffff80d3ba84 at Xapic_isr1+0xa4
#11 0xffffffff8037035b at acpi_cpu_idle+0x15b
#12 0xffffffff80d3efaf at cpu_idle_acpi+0x3f
#13 0xffffffff80d3f050 at cpu_idle+0x90
#14 0xffffffff80973399 at sched_idletd+0x419
#15 0xffffffff80911034 at fork_exit+0x84
#16 0xffffffff80d3b91e at fork_trampoline+0xe
Uptime: 2m40s
```

Where /usr/src/sys/amd64/conf/INVARIANTS is a copy of GENERIC, plus
```
options        INVARIANTS              # Check and enforce proper kernel state.
options        INVARIANT_SUPPORT
```

**Comment by lattera** [comment] 2016-05-26 19:55
Cool. I'm closing this issue since the problem is with upstream FreeBSD.

**Closed by lattera** 2016-05-26 19:55 UTC
Labels: bug
