### ISSUE TITLE
sysctl Operation not permitted in Jails under 10-STABLE

### ISSUE THREAD

**Issue by dmilith** [HardenedBSD/hardenedBSD#164] opened 2015-09-15 22:54 UTC
```
1. create jail
2. login to jail
sysctl hardening.pax.pageexec.status=1
sysctl hardening.pax.mprotect.status=1
3. restart jail
4. login back to jail
sysctl hardening.pax.pageexec.status=1
sysctl: hardening.pax.pageexec.status=1: Operation not permitted
zsh: exit 1     sysctl hardening.pax.pageexec.status=1

```

**Comment by lattera** [comment] 2015-09-15 22:56
18:35 < dmilith> try this one - spawn a jail, set some sysctl from hardening, then restart jail and log onto it again and try to set sysctl
18:35 < dmilith> 10.2-STABLE
18:35 < dmilith> build today from branch -29
18:36 < lattera> I'll have to spin up a new bhyve instance to test out
18:36 < lattera> soonest I can get to testing would be early next week
18:36 < dmilith> http://s.verknowsys.com/560b9d0d9e08343bb5704591c110f775.png
18:36 < dmilith> for the 1st time, it works flawlessly
18:36 < dmilith> then i do restart of jail
18:37 < dmilith> login again and try do the same
18:37 < dmilith> http://s.verknowsys.com/56febef5c7073beba00c4cf577fd1e23.png
18:37 < dmilith> binary has setuid btw, the same is as root under jail

**Comment by lattera** [comment] 2015-10-07 04:25
I need to test on 10-STABLE, but here are the results from 11-CURRENT:

        laptop-dev-01[shawn]:/home/shawn $ sudo jail -c name=test-01 host.hostname=test-01 path=/ persist
        laptop-dev-01[shawn]:/home/shawn $ sudo jexec test-01 sysctl hardening.pax.aslr.status=0
        hardening.pax.aslr.status: 2 -> 0
        laptop-dev-01[shawn]:/home/shawn $ sudo jail -r test-01
        laptop-dev-01[shawn]:/home/shawn $ sudo jail -c name=test-01 host.hostname=test-01 path=/ persist
        laptop-dev-01[shawn]:/home/shawn $ sudo jexec test-01 sysctl hardening.pax.aslr.status=0
        hardening.pax.aslr.status: 2 -> 0
        laptop-dev-01[shawn]:/home/shawn $ sudo jail -r test-01

**Comment by lattera** [comment] 2015-10-07 14:24
Following the same steps under 10-STABLE works for me.

**Comment by lattera** [comment] 2015-10-08 17:40
Closing this issue per submitter's request. It looks like this may be an issue with the jail management application the submitter is using in conjunction with kern.securelevel within the jail. I'm unable to reproduce.

If anyone else experiences this issue, feel free to reopen and we'll reinvestigate.

**Closed by lattera** 2015-10-08 17:40 UTC
Labels: bug
